### ISSUE TITLE
Nothing exists here :(

### ISSUE THREAD

**Issue by SneakerElph** [DylanFrese/Corda#1]
I'd love to be able to check out what you've done here - running Pianobarfly using Popen is tough and I just wish I could access libpiano directly in my scripts.

**Comment by DylanFrese** [comment]
Hey @SneakerElph. I started this project to be able to hook up my mother's Raspberry Pi Radio to a LCD display with buttons. I never found enough time to finish, though, as I moved states, jobs, etc.

I created this repository before I decided to move to GitLab, so the actual content exists [here](https://gitlab.com/Bloodshot/Corda). The only thing present is the FFI code to call the C methods directly. I plan on adding a high-level Rubyist API that is far easier to use, but that's not there yet.

Let me know how else I can help.

**Comment by SneakerElph** [comment]
Neat! Well I'll mess with it and see what I can come up with. Thanks for pointing me there!
